### ISSUE TITLE
Mongo Explorer plugin does not work well in intellij idea 14.1

### ISSUE THREAD

**Issue by xiaochunyong** [dboissier/mongo4idea#107]
Mongo Explorer plugin does not work well in intellij idea 14.1 ~
It is important to me, can you fix it~
thanks very much.

When i selected a database,  clicked Mongo Shell, i got a error message :

org/codinjutsu/tools/mongo/view/console/MongoConsoleView
java.lang.NoClassDefFoundError: org/codinjutsu/tools/mongo/view/console/MongoConsoleView
	at org.codinjutsu.tools.mongo.view.console.MongoConsoleRunner.createConsoleView(MongoConsoleRunner.java:54)
	at org.codinjutsu.tools.mongo.view.console.MongoConsoleRunner.createConsoleView(MongoConsoleRunner.java:38)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.a(AbstractConsoleRunnerWithHistory.java:89)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.access$000(AbstractConsoleRunnerWithHistory.java:52)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory$1.run(AbstractConsoleRunnerWithHistory.java:82)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2379)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.initAndRun(AbstractConsoleRunnerWithHistory.java:79)
	at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.runShell(MongoConsoleAction.java:69)
	at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.actionPerformed(MongoConsoleAction.java:63)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
	at java.awt.Component.processEvent(Component.java:6179)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
	at java.awt.Container.dispatchEventImpl(Container.java:2128)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by xiaochunyong** [comment]
Can you add a new feature, that can set a default limit value for view collection content~

**Comment by dboissier** [comment]
Hi,

> Bug in 14.1

It seems I have to provide a new build based on the 14.1 version. It happens when some idea API signature change.

> Can you add a new feature, that can set a default limit value for view collection content

By default, it is 200 records

**Comment by xiaochunyong** [comment]
Thank you for your reply，I understand[?]

**Comment by dboissier** [comment]
while waiting for new build, if you are under Linux OS, you may use the terminal tool window to run mongo cli ;)

**Comment by Satak** [comment]
Mongo shell does not open for me
windows 8.1 x64
webstorm 10.0.1

com/intellij/execution/runners/ConsoleExecuteActionHandler
java.lang.NoClassDefFoundError: com/intellij/execution/runners/ConsoleExecuteActionHandler
	at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.runShell(MongoConsoleAction.java:67)
	at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.actionPerformed(MongoConsoleAction.java:63)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.execution.runners.ConsoleExecuteActionHandler PluginClassLoader[Mongo Plugin, 0.7.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more

**Comment by musichen** [comment]
The same problem I have  with InteliJIdea 14.1.3     in Mongo Plugin:   
When try to run Mongo Shell:      
NoClassDefFoundError: com/intellij/execution/runners/ConsoleExecuteActionHandler

Though it worked in 14.0.3

**Comment by amanomio** [comment]
get the same error When try to run Mongo Shell:

NoClassDefFoundError: com / IntelliJ / execution / runners / ConsoleExecuteActionHandler

must simply download the old version 14.0.3.

**Comment by natdm** [comment]
Love the addon. Thanks for all your hard work! Only feature that's busto'd...

WebStorm 10.0.2:

org/codinjutsu/tools/mongo/view/console/MongoConsoleView
java.lang.NoClassDefFoundError: org/codinjutsu/tools/mongo/view/console/MongoConsoleView
	at org.codinjutsu.tools.mongo.view.console.MongoConsoleRunner.createConsoleView(MongoConsoleRunner.java:54)
	at org.codinjutsu.tools.mongo.view.console.MongoConsoleRunner.createConsoleView(MongoConsoleRunner.java:38)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.a(AbstractConsoleRunnerWithHistory.java:89)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.access$000(AbstractConsoleRunnerWithHistory.java:52)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory$1.run(AbstractConsoleRunnerWithHistory.java:82)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2379)
	at com.intellij.execution.runners.AbstractConsoleRunnerWithHistory.initAndRun(AbstractConsoleRunnerWithHistory.java:79)
	at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.runShell(MongoConsoleAction.java:69)
	at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.actionPerformed(MongoConsoleAction.java:63)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dboissier** [comment]
0.7.1 should be available right now.

Sorry for the delay

**Comment by natdm** [comment]
Fantastic, thank you!!!

On Tue, Jun 16, 2015 at 4:48 AM, David Boissier <notifications@github.com>
wrote:

> Closed #107 <https://github.com/dboissier/mongo4idea/issues/107>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dboissier/mongo4idea/issues/107#event-332004427>.
>



-- 
___________________________
Nathan Hyland
(602)740-5705

**Comment by dboissier** [comment]
You should thank [pwilkin](https://github.com/pwilkin). He made the pull request to make it work :D

**Comment by kishoretulsiani** [comment]
i upgraded to intellij idea 15 and getting this error, can you please provide some fix for this

com/intellij/execution/runners/ConsoleExecuteActionHandler
java.lang.NoClassDefFoundError: com/intellij/execution/runners/ConsoleExecuteActionHandler
	at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.runShell(MongoConsoleAction.java:67)
	at org.codinjutsu.tools.mongo.view.action.MongoConsoleAction.actionPerformed(MongoConsoleAction.java:63)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:299)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.execution.runners.ConsoleExecuteActionHandler PluginClassLoader[Mongo Plugin, 0.7.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more

**Comment by dboissier** [comment]
Hi,

same root cause than previous. A release for Idea 15 is planned soon.

Please be patient :)

**Comment by kishoretulsiani** [comment]
After the update it is working fine. Thanks!

**Comment by redi-feathe** [comment]
Is this also an issue in idea 16?
