### ISSUE TITLE
the plugin doesn't support webstorm 2019.1

### ISSUE THREAD

**Issue by GartenChoi** [dboissier/mongo4idea#269]
since i upgrade webstorm to version 2019.1, "view collection content" doesnt work. so I revert to version 2018.3...

**Comment by dacopan** [comment]
https://plugins.jetbrains.com/plugin/12242-mongo-2-0

**Comment by efstathiosntonas** [comment]
thanks @dacopan

**Comment by efstathiosntonas** [comment]
If anyone wants to download it here's the link: https://ufile.io/remgtgvc

As of now, jetbrains hasn't verified the plugin thus it's not appearing in plugins

**Comment by kukukk** [comment]
@dacopan: It is still pending. Any update when will it be available?

**Comment by dacopan** [comment]
I don't know I've not received a response of JetBrains

**Comment by GartenChoi** [comment]
thanks everyone

**Comment by HappyManYun** [comment]
@efstathiosntonas This zip does not work （idea 2019.1.2）

**Comment by kukukk** [comment]
@HappyManYun I can't help you with that zip, because I built it from source, but I also encountered difficulties, because I had some garbage left by the original plugin. After removing .idea/mongoSettings.xml  file (if I remember correctly) and configured a new MongoDB connection, it worked.

**Comment by bluebad** [comment]
> If anyone wants to download it here's the link: https://ufile.io/remgtgvc
> 
> As of now, jetbrains hasn't verified the plugin thus it's not appearing in plugins.
> 
> Download it and select install plugin from disk, **then select the .zip file** and you're done.

PyCharm 2019.1.2 (Community Edition)
Build #PC-191.7141.48, built on May 7, 2019
JRE: 11.0.2+9-b159.56 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

It works.Thanks a lot.

**Comment by davidsolanes2** [comment]
Hi, I have the same problem
But when I'm going the link, is not possible to download
Where it's possible to find
Thanks a lot

**Comment by dacopan** [comment]
https://gofile.io/?c=jmd5tr
I'm working on errors reported by JetBrains. plugin will be public available  soon...

**Comment by dacopan** [comment]
> @efstathiosntonas This zip does not work （idea 2019.1.2）

can you upload the log file? 

please follow:

- remove plugin
- remove .idea/mongoSettings.xml from project
- restart IDE
- install plugin from JAR file

**Comment by davidsolanes2** [comment]
Good morning,

I followed your steps, but the system return this message



Regards

**Comment by cunneen** [comment]
@davidsolanes2 and @HappyManYun , try this zip (attached below). It's the same as @dacopan's (thank you dacopan!) except it uses the [mongo-java-driver uber-jar](https://mongodb.github.io/mongo-java-driver/), and it includes the fix for #242 . See [here](https://github.com/cunneen/mongo4idea/commit/ad49b1e8a3992547c76305c7d62f0125170d2732).

[mongo4idea.zip](https://github.com/dboissier/mongo4idea/files/3300294/mongo4idea.zip)

**Comment by kmbyrne** [comment]
@cunneen Thank you for that zip, worked great for me.

**Comment by pastuh** [comment]
Thanks, works perfect !

**Comment by brucekong** [comment]
still pending。

**Comment by josephks** [comment]
I asked JetBrains about the status of the plugin approval. They replied:

There are some compatibility issues (can see on https://plugins.jetbrains.com/plugin/12242-mongo-2-0/update/61868). After installing this plugin in IDE an error happened. The letters were sent to Darwin Correa, the author of this plugin on May 4th and April 16th to fix it. Hi didn't respond yet.

**Comment by dacopan** [comment]
I can't reproduce the issue, many user report that the plugin works well.
if you cant send some feedback about errors I'll work on fixed it


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/08/19
08:35:15

**Comment by josephks** [comment]
I'm just repeating what JetBrains said.  I don't know what issues they are talking about.

**Comment by dacopan** [comment]
> NoClassDefFoundError: org/bson/json/JsonParseException
>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/08/19
08:50:19

**Comment by rrajkomar** [comment]
Hi,
Any news on the availability of an officially supported fix ?

**Comment by hlongmore** [comment]
FYI, when trying to access the file at https://ufile.io/remgtgvc I got this message:

> mongo4idea-master.zip
> Premium Access Only
> The hosting period for this file has now expired, only premium users can download it.

I will try the one attached to https://github.com/dboissier/mongo4idea/issues/269#issuecomment-502984541

**Comment by dboissier** [comment]
Hi,

the plugin has been fixed. please download this [release](https://github.com/dboissier/mongo4idea/blob/master/snapshot/mongo4idea-0.12.2-SNAPSHOT.zip) and tell me whether it works on your IDE.

Thanks

**Comment by dboissier** [comment]
@dacopan I saw you made a fork of the plugin.

Maintaining this plugin is too much time consuming with my current situation. I would be happy to transfer your the ownership of this stuff. What do you say?

FYI, Jetbrains has started to work on MongoDB support in their database plugin. This is a really good news :)

**Comment by efstathiosntonas** [comment]
Confirmed working on Webstorm 2019.2.3. Thanks @dboissier

**Comment by dboissier** [comment]
Thanks for your feedback. I upload the plugin to the repository right now.

**Comment by xstable** [comment]
~I have Plugin-Version 0.12.2 and it still don't work.~
I've figured out, you have to remove the old 0.12.2 Plugin, if you installed it as zip before. Then restart phpstorm and install Plugin again. Then it works.

Thanks @dboissier for fixing this.
